<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914144655 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, performed_on DATE NOT NULL, description VARCHAR(160) NOT NULL, duration_minutes INT DEFAULT NULL, calories_burned DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_activity_user_day ON activity_entry (user_id, performed_on)');
        $this->addSql('CREATE INDEX IDX_3523ABC3A76ED395 ON activity_entry (user_id)');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(80) NOT NULL, verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('CREATE TABLE body_measurement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, measured_on DATE NOT NULL, weight_kg DOUBLE PRECISION NOT NULL, muscle_mass_kg DOUBLE PRECISION DEFAULT NULL, fat_mass_kg DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_measurement_user_day ON body_measurement (user_id, measured_on)');
        $this->addSql('CREATE INDEX IDX_E574BF11A76ED395 ON body_measurement (user_id)');
        $this->addSql('CREATE TABLE diary_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, logged_on DATE NOT NULL, meal_type VARCHAR(16) NOT NULL, quantity DOUBLE PRECISION NOT NULL, unit VARCHAR(16) NOT NULL, portion_label VARCHAR(64) DEFAULT NULL, grams DOUBLE PRECISION NOT NULL, label VARCHAR(220) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, n_kcal DOUBLE PRECISION NOT NULL, n_protein_g DOUBLE PRECISION NOT NULL, n_carbs_g DOUBLE PRECISION NOT NULL, n_fat_g DOUBLE PRECISION NOT NULL, n_fiber_g DOUBLE PRECISION DEFAULT NULL, n_sugar_g DOUBLE PRECISION DEFAULT NULL, n_salt_g DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, food_id INT DEFAULT NULL, recipe_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_diary_user_day ON diary_entry (user_id, logged_on)');
        $this->addSql('CREATE INDEX IDX_6A3E3D51A76ED395 ON diary_entry (user_id)');
        $this->addSql('CREATE INDEX IDX_6A3E3D51BA8E87C4 ON diary_entry (food_id)');
        $this->addSql('CREATE INDEX IDX_6A3E3D5159D8A214 ON diary_entry (recipe_id)');
        $this->addSql('CREATE TABLE email_verification_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_verification_token_hash ON email_verification_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_C4995C67A76ED395 ON email_verification_token (user_id)');
        $this->addSql('CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, brand VARCHAR(120) DEFAULT NULL, barcode VARCHAR(32) DEFAULT NULL, density_gper_ml DOUBLE PRECISION NOT NULL, source VARCHAR(32) NOT NULL, external_id VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, per100_kcal DOUBLE PRECISION NOT NULL, per100_protein_g DOUBLE PRECISION NOT NULL, per100_carbs_g DOUBLE PRECISION NOT NULL, per100_fat_g DOUBLE PRECISION NOT NULL, per100_fiber_g DOUBLE PRECISION DEFAULT NULL, per100_sugar_g DOUBLE PRECISION DEFAULT NULL, per100_salt_g DOUBLE PRECISION DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_food_name ON food (name)');
        $this->addSql('CREATE UNIQUE INDEX uniq_food_barcode ON food (barcode)');
        $this->addSql('CREATE INDEX IDX_D43829F7B03A8386 ON food (created_by_id)');
        $this->addSql('CREATE TABLE food_portion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(64) NOT NULL, grams DOUBLE PRECISION NOT NULL, food_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_portion_food_label ON food_portion (food_id, label)');
        $this->addSql('CREATE INDEX IDX_AF1F211EBA8E87C4 ON food_portion (food_id)');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, servings INT NOT NULL, public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_recipe_name ON recipe (name)');
        $this->addSql('CREATE INDEX IDX_DA88B137B03A8386 ON recipe (created_by_id)');
        $this->addSql('CREATE TABLE recipe_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grams DOUBLE PRECISION NOT NULL, recipe_id INT NOT NULL, food_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_22D1FE1359D8A214 ON recipe_ingredient (recipe_id)');
        $this->addSql('CREATE INDEX IDX_22D1FE13BA8E87C4 ON recipe_ingredient (food_id)');
        $this->addSql('CREATE TABLE user_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, birth_date DATE NOT NULL, sex VARCHAR(16) NOT NULL, height_cm DOUBLE PRECISION NOT NULL, activity_level VARCHAR(32) NOT NULL, goal VARCHAR(32) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AB405A76ED395 ON user_profile (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity_entry ADD CONSTRAINT FK_3523ABC3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE body_measurement ADD CONSTRAINT FK_E574BF11A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE diary_entry ADD CONSTRAINT FK_6A3E3D51A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE diary_entry ADD CONSTRAINT FK_6A3E3D51BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE diary_entry ADD CONSTRAINT FK_6A3E3D5159D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email_verification_token ADD CONSTRAINT FK_C4995C67A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE food ADD CONSTRAINT FK_D43829F7B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE food_portion ADD CONSTRAINT FK_AF1F211EBA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B137B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE1359D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE13BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB405A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_entry DROP CONSTRAINT FK_3523ABC3A76ED395');
        $this->addSql('ALTER TABLE body_measurement DROP CONSTRAINT FK_E574BF11A76ED395');
        $this->addSql('ALTER TABLE diary_entry DROP CONSTRAINT FK_6A3E3D51A76ED395');
        $this->addSql('ALTER TABLE diary_entry DROP CONSTRAINT FK_6A3E3D51BA8E87C4');
        $this->addSql('ALTER TABLE diary_entry DROP CONSTRAINT FK_6A3E3D5159D8A214');
        $this->addSql('ALTER TABLE email_verification_token DROP CONSTRAINT FK_C4995C67A76ED395');
        $this->addSql('ALTER TABLE food DROP CONSTRAINT FK_D43829F7B03A8386');
        $this->addSql('ALTER TABLE food_portion DROP CONSTRAINT FK_AF1F211EBA8E87C4');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B137B03A8386');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE1359D8A214');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE13BA8E87C4');
        $this->addSql('ALTER TABLE user_profile DROP CONSTRAINT FK_D95AB405A76ED395');
        $this->addSql('DROP TABLE activity_entry');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE body_measurement');
        $this->addSql('DROP TABLE diary_entry');
        $this->addSql('DROP TABLE email_verification_token');
        $this->addSql('DROP TABLE food');
        $this->addSql('DROP TABLE food_portion');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE recipe_ingredient');
        $this->addSql('DROP TABLE user_profile');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
